### ISSUE TITLE
TLS Load Test

### ISSUE THREAD

**Issue by alongir** [kubeshark/k8s-cluster-load-test#1]
**Current:**

- The following repo, is used to load test the Worker: https://github.com/kubeshark/k8s-cluster-load-test
- So far it's HTTP only
- It's more challenging to test HTTPS
- Creating an HTTPS  client-server is challenging

**Requested:**

- Extend the K8s-cluster-load test to include HTTPS traffic.
- Add an HTTPS server
- Create a client that loads the https server
- Enable control similar to what the repo offers currently.

**Comment by corest** [comment]
Solved

**Comment by corest** [comment]
@alongir I don't have such image and it probably doesn't exist
